# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'server_1 metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['server_1:8182']

  - job_name: 'server_2 metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['server_2:8283']

  - job_name: 'server_3 metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['server_3:8384']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # Node exporter running on your host
